/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Grey-scale placify palette (replaces blue/lavender)
        "p-blue": "#888888",
        "p-dark": "#111111",
        "p-bg": "#FFFFFF",
        "p-lav": "#AAAAAA",
        "p-blue-10": "rgba(0,0,0,0.05)",
        "p-blue-20": "rgba(0,0,0,0.08)",
        "p-lav-20": "rgba(0,0,0,0.06)",
        amber: {
          50: "#FFF7E8",
          100: "#FFEBC2",
          200: "#E7BA67",
          300: "#D99C2A",
          400: "#C48502",
          500: "#B77902",
          600: "#9C6500",
          700: "#774C00",
          800: "#543704",
          900: "#3A2605",
          950: "#241703",
        },

        // Neutral Material Design tokens
        "outline-variant": "#D8D8D8",
        "on-secondary-container": "#222222",
        "surface-tint": "#555555",
        "on-surface-variant": "#555555",
        "surface-container": "#F0F0F0",
        background: "#FFFFFF",
        "secondary-fixed-dim": "#CCCCCC",
        surface: "#FFFFFF",
        "on-background": "#111111",
        "secondary-container": "#E8E8E8",
        "surface-container-high": "#EBEBEB",
        "inverse-on-surface": "#F5F5F5",
        "on-primary-fixed": "#000000",
        "surface-bright": "#FFFFFF",
        "on-primary-container": "#111111",
        "on-surface": "#111111",
        "surface-dim": "#D0D0D0",
        "on-tertiary-fixed": "#111111",
        "surface-container-low": "#F8F8F8",
        "on-secondary": "#FFFFFF",
        "secondary-fixed": "#E8E8E8",
        "error-container": "#FFE8E8",
        "on-primary": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "tertiary-fixed-dim": "#CCCCCC",
        "on-tertiary-container": "#333333",
        secondary: "#555555",
        "on-primary-fixed-variant": "#111111",
        "primary-fixed": "#E0E0E0",
        "on-secondary-fixed": "#111111",
        "on-tertiary": "#FFFFFF",
        "inverse-primary": "#CCCCCC",
        error: "#CC0000",
        "on-secondary-fixed-variant": "#444444",
        "surface-container-highest": "#E0E0E0",
        "on-tertiary-fixed-variant": "#333333",
        "inverse-surface": "#222222",
        "primary-fixed-dim": "#BBBBBB",
        tertiary: "#555555",
        "tertiary-container": "#E8E8E8",
        "on-error": "#FFFFFF",
        outline: "#999999",
        "primary-container": "#E0E0E0",
        "tertiary-fixed": "#EEEEEE",
        primary: "#111111",
        "surface-variant": "#EBEBEB",
        "on-error-container": "#880000",
      },
      fontFamily: {
        display: ['"Clash Display"', "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Epilogue", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        card: "0 2px 20px rgba(0,0,0,0.06)",
        "card-md": "0 4px 32px rgba(0,0,0,0.09)",
        blue: "0 8px 32px rgba(0,0,0,0.12)",
        "blue-sm": "0 4px 16px rgba(0,0,0,0.08)",
        lav: "0 8px 32px rgba(0,0,0,0.10)",
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: 0, transform: "translateY(24px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        floatY: {
          "0%,100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-14px)" },
        },
        orb: {
          "0%,100%": { transform: "scale(1) translate(0,0)" },
          "50%": { transform: "scale(1.08) translate(10px,-10px)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease forwards",
        "float-y": "floatY 5s ease-in-out infinite",
        orb: "orb 10s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
